apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: fm4td1ejs-go-gitops
  description: This is GitOps manifest for fm4td1ejs-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=fm4td1ejs-go
    backstage.io/kubernetes-id: fm4td1ejs-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: fm4td1ejs-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:fm4td1ejs-go
