apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fm4td1ejs-go
  janus-idp.io/tekton: fm4td1ejs-go
  backstage.io/kubernetes-id: fm4td1ejs-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fm4td1ejs-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
