apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fm4td1ejs-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fm4td1ejs-go 
  name: fm4td1ejs-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fm4td1ejs-go 
